# Generated by Django 3.1.8 on 2021-04-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        ('journal', '0002_auto_20210421_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='workout_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workout'),
        ),
    ]
