# Generated by Django 3.1.8 on 2021-04-21 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20210421_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 15, 30, 11, 579310, tzinfo=utc)),
        ),
    ]
