# Generated by Django 3.1.8 on 2021-04-23 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20210424_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 23, 35, 8, 908829, tzinfo=utc)),
        ),
    ]
