# Generated by Django 3.1.8 on 2021-04-24 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20210424_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 9, 37, 50, 421047, tzinfo=utc)),
        ),
    ]
