# Generated by Django 3.1.8 on 2021-05-02 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20210424_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='workout_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 18, 27, 2, 538193, tzinfo=utc)),
        ),
    ]
