# Generated by Django 3.1.8 on 2021-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20210502_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
