# Generated by Django 3.1.8 on 2021-05-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_remove_progress_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, help_text='In a few words', max_length=1024, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('upperarm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('forearm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('upperleg', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=2, help_text='Height in CM', max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
