# Generated by Django 3.1.8 on 2021-05-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='journal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal'),
        ),
    ]
