# Generated by Django 3.1.8 on 2021-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20210505_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='workout_complete',
        ),
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
