# Generated by Django 3.1.8 on 2021-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_auto_20210509_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
