# Generated by Django 3.1.8 on 2021-05-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_progress_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='complete',
        ),
    ]
