# Generated by Django 3.1.8 on 2021-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_remove_progress_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight_targetted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
