# Generated by Django 3.1.8 on 2021-05-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_auto_20210514_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='journal.journal'),
        ),
    ]
