# Generated by Django 3.1.8 on 2021-06-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_auto_20210515_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='checkin_status',
            field=models.IntegerField(default=0),
        ),
    ]
