# Generated by Django 3.1.8 on 2021-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20210617_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='workout_status',
            field=models.IntegerField(default=0),
        ),
    ]
