# Generated by Django 3.1.8 on 2021-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_journal_workout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='rpe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
