# Generated by Django 3.1.8 on 2021-06-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20210620_1222'),
        ('journal', '0026_progress_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='workoutset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to='workout.workoutset'),
        ),
    ]
