# Generated by Django 3.1.8 on 2021-06-06 14:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210503_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='images/accounts/joe-paris-logo-coming-soon.png', upload_to='images/accounts', verbose_name='Profile Pic'),
        ),
    ]
