# Generated by Django 3.1.8 on 2021-04-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='reps_recorded',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='weight_recorded',
        ),
        migrations.RemoveField(
            model_name='approach',
            name='weight_targetted',
        ),
    ]
