# Generated by Django 3.1.8 on 2021-05-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210424_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='complete',
        ),
    ]
