# Generated by Django 3.1.8 on 2021-05-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20210502_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approachs', to='workout.routine'),
        ),
    ]
