# Generated by Django 3.1.8 on 2021-05-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20210509_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='exercise_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='workout.workout', verbose_name='Workout'),
        ),
    ]
