# Generated by Django 3.1.8 on 2021-06-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20210620_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='workout.workout'),
        ),
    ]
